CREATE DATABASE IF NOT EXISTS sayit;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY UNIQUE DEFAULT (UUID()),
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  password VARCHAR (16) NOT NULL,
  country VARCHAR(45) NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  bio VARCHAR(140) NULL,
  code_to_reset_password INT NULL,
  github VARCHAR(100) NULL,
  linkedin VARCHAR(100) NULL
);

CREATE TABLE IF NOT EXISTS posts (
  id VARCHAR(36) PRIMARY KEY UNIQUE DEFAULT (UUID()),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  content VARCHAR(255) NULL,
  user_id VARCHAR(36),
  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS interactions (
  id VARCHAR(36) PRIMARY KEY UNIQUE DEFAULT (UUID()),
  post_id VARCHAR(36),
  user_id VARCHAR(36),
  `like` BOOLEAN NULL,
  comment VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(post_id) REFERENCES posts(id),
  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE connections (
  id VARCHAR(36) PRIMARY KEY UNIQUE DEFAULT (UUID()),
  user_id VARCHAR(36),
  followed_user VARCHAR(36),
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(followed_user) REFERENCES users(id)
);
