CREATE DATABASE sayit;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY UNIQUE DEFAULT (UUID()),
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  password VARCHAR (16) NOT NULL,
  country VARCHAR(45) NULL,
  isActive BOOLEAN NOT NULL DEFAULT true,
  bio VARCHAR(140) NULL,
  codeToResetPassword INT NULL,
  github VARCHAR(100) NULL,
  linkedin VARCHAR(100) NULL
);

CREATE TABLE IF NOT EXISTS posts (
  id VARCHAR(36) PRIMARY KEY UNIQUE DEFAULT (UUID()),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  content VARCHAR(255) NULL,
  user_id VARCHAR(36),
  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS interactions (
  id VARCHAR(36) PRIMARY KEY UNIQUE DEFAULT (UUID()),
  post_id VARCHAR(36),
  user_id VARCHAR(36),
  `like` BOOLEAN NULL,
  comment VARCHAR(255) NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(post_id) REFERENCES posts(id),
  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE connections (
  id VARCHAR(36) PRIMARY KEY UNIQUE DEFAULT (UUID()),
  user_id VARCHAR(36),
  followedUser VARCHAR(36),
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(followedUser) REFERENCES users(id)
);